# Generated by Django 4.1.1 on 2023-04-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='musicians_needed',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
