# Generated by Django 4.1.1 on 2023-02-14 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='occurring',
        ),
    ]
