# Generated by Django 4.1.1 on 2023-02-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_event_occurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='occurring',
            field=models.DateField(null=True),
        ),
    ]
