# Generated by Django 4.1.1 on 2023-03-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_event_occurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=91342, max_length=50),
            preserve_default=False,
        ),
    ]
