# Generated by Django 4.1.1 on 2023-04-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
