# Generated by Django 4.1.1 on 2023-03-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='featured_image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
