# Generated by Django 4.1.1 on 2023-04-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
