# Generated by Django 4.1.1 on 2023-03-20 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_event_id_alter_group_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='genres',
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='musician',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='base.skill'),
        ),
    ]
