# Generated by Django 4.1.1 on 2023-04-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_event_name_alter_event_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='demo',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
