# Generated by Django 4.1.1 on 2023-04-19 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_contract_description_alter_demo_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='owner',
        ),
    ]
