# Generated by Django 4.1.1 on 2023-03-20 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_musician_genres_skill_musician_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='primarygenre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='primaryinstrument',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='musician',
            name='instruments',
        ),
        migrations.CreateModel(
            name='InstrumentSkill',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='musician',
            name='instruments',
            field=models.ManyToManyField(blank=True, null=True, to='base.instrumentskill'),
        ),
    ]
