# Generated by Django 4.1.1 on 2023-03-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_musician_primarygenre_musician_primaryinstrument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='genres',
            field=models.ManyToManyField(to='base.skill'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='instruments',
            field=models.ManyToManyField(to='base.instrumentskill'),
        ),
    ]
