# Generated by Django 4.1.1 on 2023-04-19 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_demo_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
