# Generated by Django 4.1.1 on 2023-03-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_instrumentskill_owner_remove_skill_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='genres',
            field=models.ManyToManyField(blank=True, to='base.skill'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='instruments',
            field=models.ManyToManyField(blank=True, to='base.instrumentskill'),
        ),
    ]
