# Generated by Django 4.1.1 on 2023-04-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_demo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='video',
            field=models.FileField(upload_to='video/'),
        ),
    ]
