# Generated by Django 4.1.1 on 2023-04-19 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_demo_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demo',
            old_name='video',
            new_name='demovid',
        ),
    ]
