# Generated by Django 4.1.1 on 2023-04-04 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Musician',
            new_name='musician',
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
