# Generated by Django 4.1.1 on 2023-04-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_video_demo_demovid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='demovid',
            field=models.FileField(upload_to='video/%y'),
        ),
    ]
