# Generated by Django 4.1.1 on 2023-04-23 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_demo_demovid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inboxmessage',
            options={'ordering': ['-created']},
        ),
    ]
