# Generated by Django 4.1.1 on 2023-04-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_distances'),
    ]

    operations = [
        migrations.AddField(
            model_name='distances',
            name='label',
            field=models.CharField(default='mytest', max_length=20),
            preserve_default=False,
        ),
    ]
