# Generated by Django 4.1.1 on 2023-04-23 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_inboxmessage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='demo',
        ),
        migrations.CreateModel(
            name='UserMusician',
            fields=[
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('account_type', models.CharField(choices=[('M', 'Musician'), ('G', 'Group')], default='M', max_length=10)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('bio', models.TextField(null=True)),
                ('avatar', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('primaryinstrument', models.CharField(blank=True, max_length=200, null=True)),
                ('primarygenre', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(choices=[('One Year', '0-1'), ('Two To Three Years', '2-3'), ('Four To Seven Years', '4-7'), ('Eight Or More Years', '8+')], default='One Year', max_length=19)),
                ('location', models.CharField(max_length=50)),
                ('musician_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('genres', models.ManyToManyField(blank=True, to='base.skill')),
                ('instruments', models.ManyToManyField(blank=True, to='base.instrumentskill')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
