# Generated by Django 4.1.1 on 2023-04-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermusician',
            name='username',
        ),
    ]
