# Generated by Django 4.1.1 on 2023-04-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='group',
        ),
    ]
