# Generated by Django 4.1.1 on 2023-04-23 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_usermusician_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('account_type', models.CharField(choices=[('M', 'Musician'), ('G', 'Group')], default='M', max_length=10)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('bio', models.TextField(null=True)),
                ('avatar', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('group_name', models.CharField(max_length=60)),
                ('genre', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('featured_image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
