# Generated by Django 4.1.1 on 2023-04-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_rename_user_review_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentskill',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
