# Generated by Django 4.1.1 on 2023-04-10 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_instrumentskill_primary_skill_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.group'),
            preserve_default=False,
        ),
    ]
