# Generated by Django 4.1.1 on 2023-04-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_usergroup_username_usermusician_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='instrument',
            field=models.CharField(default='Trumper', max_length=30),
            preserve_default=False,
        ),
    ]
