# Generated by Django 4.1.1 on 2023-04-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_contract_accepted_contract_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxmessage',
            name='contract_related',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
