# Generated by Django 4.1.1 on 2023-04-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_inboxmessage_contract_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxmessage',
            name='contract_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
