# Generated by Django 4.1.1 on 2023-05-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_demo_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demo',
            old_name='title',
            new_name='name',
        ),
    ]
